# This is a basic workflow to help you get started with Actions

name: Mac OSX builds

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  osx_build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    env:
      GEODA_VER: '1.18.0'

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build GeoDa
      - name: Build GeoDa
        run: |
          cp GeoDamake.macosx.opt GeoDamake.opt
          cd BuildTools
          cd macosx
          export GEODA_HOME=$PWD
          export GEODA_ARCH=x86_64
          ./install.sh
      
      # Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: GeoDa-${{ env.GEODA_VER }}-MacOS
          path: ${{ github.workspace }}/BuildTools/macosx/create-dmg/GeoDa${{ env.GEODA_VER }}-Installer.dmg





