# This is a basic workflow to help you get started with Actions

name: Ubuntu 18.04(Bionic) builds

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bionic_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build GeoDa
      - name: Build GeoDa
        run: |
          cd BuildTools
          cd ubuntu
          export GEODA_HOME=$PWD
          ./install.sh bionic 1.18.2
      
      # Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: GeoDa-1.18.2-Bionic
          path: ${{ github.workspace }}/BuildTools/ubuntu/geoda_1.18.2-1bionic1_amd64.deb





